name: deblur_gs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - torchmetrics=0.11.2
  - tqdm
  - timm
  - tensorboard
  - visdom
  - scipy
  - matplotlib
  - pip:
      - aiohttp
      - websockets
      - python-dotenv
      - opencv-python
      - easydict
      - ../wheels/diff_gaussian_rasterization-0.0.0-cp37-cp37m-win_amd64.whl
      - ../wheels/pytorch3d-0.7.6-cp37-cp37m-win_amd64.whl
      - ../wheels/simple_knn-0.0.0-cp37-cp37m-win_amd64.whl
      - ../libs/deblur-gs
