name: fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - setuptools
  - sqlalchemy
  - tenacity
  - boto3
  - pyglm
  - black
  - fastapi
  - pymysql
  - python-dotenv
  - pip
  - pip:
      - uvicorn[standard]
      - ../libs/analyzer
      - ../libs/downloader
