name: fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - setuptools
  - sqlalchemy
  - tenacity
  - boto3
  - pyglm
  - pip
  - pip:
      - fastapi
      - uvicorn[standard]
      - pymysql
      - python-dotenv
      - -e ../libs/analyzer
      - -e ../libs/downloader
